### ISSUE TITLE
ros::TimeBase: undefined behaviour for large doubles

### ISSUE THREAD

**Issue by cwecht** [ros/roscpp_core#105]
`TimeBase::fromSec(double)` casts a `double` value to an `int64_t` value. If the double value is exceeds the `int64_t` range this is undefined behaviour ([for reference](https://en.cppreference.com/w/cpp/language/implicit_conversion#Floating.E2.80.93integral_conversions)).

**Comment by dirk-thomas** [comment]
@cwecht Please consider to contribute a pull request for this.

**Comment by peci1** [comment]
Fixed by #132.
