### ISSUE TITLE
LICENSE for v0.6.11

### ISSUE THREAD

**Issue by oanastanca** [ros/roscpp_core#128]
Hello, 

Can you please specify which BDS(full text), mentioned in https://github.com/ros/roscpp_core/blob/0.6.11/roscpp_core/package.xml applies on roscpp_core 0.6.11?
There is no License file regarding the BSD that applies on roscpp_core 0.6.11.

Thank you

**Comment by christophebedard** [comment]
It's BSD-3 (like all the ROS core) according to this: http://wiki.ros.org/DevelopersGuide#Licensing

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/status-of-os-license-clearing-for-ros2/33753/6
