### ISSUE TITLE
ros serialization get wrong message size when compile on arm64 with gcc -O3

### ISSUE THREAD

**Issue by randoms** [ros/roscpp_core#130]
Example Project:  https://github.com/AutoxingTech/simple_publisher_crash

output message size

```
Publication::enqueueMessage 1 2427156042
Publication::enqueueMessage 2 2427156042
Publication::enqueueMessage 3
```

**Comment by randoms** [comment]
This is a bug of gcc. The issue was caused by `-ftree-loop-vectorize` optimization option which is included by -O3 option. The issue was reported [here](https://gcc.gnu.org/bugzilla//show_bug.cgi?id=102435) and still not fixed in gcc 9.3. Upgrade to gcc 10.x should fix this issue.

**Comment by peci1** [comment]
Would it be a solution to mark some function in the serialization code as non-optimized, or e.g. `-O2`-optimized? https://stackoverflow.com/a/13825238/1076564 . Can you try?

**Comment by peci1** [comment]
@randoms #136 should fix this. Could you verify?

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/who-are-current-roscpp-core-maintaners/31247/5
