### ISSUE TITLE
Buildroot: when building cpp_common: `CMake Error at FindPackageHandleStandardArgs.cmake:230 (message): Could NOT find Boost (missing: thread) (found version "1.80.0")`

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [ros/roscpp_core#134]
Full details in my question here: [Buildroot: `CMake Error at FindPackageHandleStandardArgs.cmake:230 (message): Could NOT find Boost (missing: thread) (found version "1.80.0")`](https://stackoverflow.com/q/75066131/4561887). 

Any ideas on how to solve this?

I'm building with Buildroot for an embedded Linux board. I just upgraded to the latest version of the Buildroot `boost` package, version 1.80.0, as shown here: https://github.com/buildroot/buildroot/blob/master/package/boost/boost.mk#L7

**Comment by peci1** [comment]
It seems the bug on SO has a solution provided and the problem is not in this repo. Can I close this issue?

**Comment by ElectricRCAircraftGuy** [comment]
Yeah. I'll close it.
