### ISSUE TITLE
Missing depend on boost

### ISSUE THREAD

**Issue by cottsay** [ros/roscpp_core#24]
My most recent Fedora builds of `cpp_common` [1] are not installing the boost development libraries as they did about 2 weeks ago. I don't see any changes to `cpp_common` that would have triggered this, so it must have been an upstream package that changed its deps or something like that.

I can't see any reason not to have `cpp_common` depend on boost, as it references boost headers [2].

I can confirm this on an f20 system without `boost-devel` by running:

``` bash
mkdir -p ~/boost_test_ws/src
cd ~/boost_test_ws
rosinstall_generator --deps --tar --rosdistro indigo cpp_common > src/.rosinstall
wstool update -t src
rosdep install --from-path src --ignore-src
```

...and finding that boost-devel is not installed as it should be.

I have confirmed that adding `boost` as a run and build dependency fixes things [3] [4], but I'm not sure what caused this to begin with, so I can only suggest that as a possible fix.

Thanks,

--scott
[1] http://csc.mcs.sdsmt.edu/jenkins/view/IbinF20x32/job/ros-indigo-cpp-common_binaryrpm_heisenbug_i386/10/console
[2] http://github.com/ros/roscpp_core/blob/indigo-devel/cpp_common/include/ros/header.h#L41
[3] http://github.com/smd-ros-rpm-release/roscpp_core-release/commit/e92922ec6b7c55aefa55e8f7c2c8a5cdae1535ca
[4] http://csc.mcs.sdsmt.edu/jenkins/view/IbinF20x32/job/ros-indigo-cpp-common_binaryrpm_heisenbug_i386/11/console

**Comment by cottsay** [comment]
Looks like class_loader is affected too: http://csc.mcs.sdsmt.edu/jenkins/view/IbinF20x32/job/ros-indigo-class-loader_binaryrpm_heisenbug_i386/12/console

**Comment by dirk-thomas** [comment]
Before the ROS package `console_bridge` was bringing in the boost dependency transitively. Since `roscpp_core` now uses the system package of `console_bridge` boost is not exposed as a transitive dependency anymore.

Anyway the packages in `roscpp_core` should state their direct dependencies explicitly anyway and not rely on transitive dependencies for this. Please see PR #25 for the proposed fix.
