### ISSUE TITLE
possible unintended message copies when sending non-const shared_ptrs

### ISSUE THREAD

**Issue by protobits** [ros/roscpp_core#31]
Hi, I'm experiencing a problem which I sense may be a bug. I have opened a question on ROS answers, but as I describe there it would appear to be a bug. 

http://answers.ros.org/question/195785/how-to-receive-non-const-shared_ptr-without-copies-when-publishing-between-nodelets/

If you need further description to understand the problem let me know. I opened the issue here since from a backtrace I found out the copy is being done on the copyMessageIfNecessary() function of message_event.h (https://github.com/ros/roscpp_core/blob/indigo-devel/roscpp_traits/include/ros/message_event.h#L215).

To sum it up, the copy is being performed after this sequence (nodeletA is publisher, nodeletB and nodeletC subscribe expecting non-const ptrs in the callback)
nodeletA publishes non-constr ptr message
nodeletB receives the same object (.get() matches)
nodeletC is loaded
nodeletA publishes non-constr ptr message (same one as first case, matches .get())
nodeletB receives a copy of the object (.get() is different)
nodeletC receives a copy of the object (.get() is different)

If nodeletC expects const-ptr in the callback, the sequence is only modified in the last step, since it receives the same ptr as was sent originally.

**Comment by dirk-thomas** [comment]
Please don't double post your question here but wait for an answer on your original question.

Short answer: any non-const subscriber **must** be handed a copy of the message since by API contract he is allowed to change the message. Otherwise any change would affect all other subscribers as well.

**Comment by protobits** [comment]
Ok, sorry, it was due to the fact I felt it was a bug since it seems the
behavior is not consistent as I described. In fact, I can see that this
behavior you mention is not the case: the non-const subscriber is not
receiving a copy the first time, but later it does.

In any case, I don't quite understand at which level this is expected to be
respected by the user or enforced by ROS itself. I agree that "the
subscriber may make modifications to the message which affect other
subscribers". However, in some cases this may be the intended consequence
and, thus, the user could be aware of this and expect to deal with the
consequences. However it seems that something is forcing the copy between
publisher-subscriber, even when it is not necessary in terms of constness
(in contrast to a const-sender and a non-const receiver, which can only be
solved by a copy in between).

If this still does not look like a bug to you, we can continue this on ROS
asnwers. My question would thus be: is ROS supposed to enforces the copy to
maintain this contract? Or should a non-const publisher and a non-const
subscriber still be able to receive the same object and leave the user the
responsibility of not breaking things with other subscribers?

Thanks

**Comment by dirk-thomas** [comment]
The signature of the published message (const or non-const) does not matter for this at all.

ROS can not allow a subscriber to affect other subscribers. So if you have multiple subscribers the non-const subscribers must receive a copy (which is enforced by ROS). In the case that there is only one subscriber it does not make a difference if ROS is handing it the original instance or a copy (I guess this is what you see as inconsistent behavior). But you should consider that an implementation detail and not rely on it.

While it might look like a nice way to communicate information from one subscriber to another subscriber by changing the message instance in-place that would violate the publish / subscribe model of the communication. That is not a support way of communication.

**Comment by protobits** [comment]
Sorry, I just read this after replying on ros answers. Your last reply clarifies the situation for me. Thanks for the information.

**Comment by dirk-thomas** [comment]
That's why not reposting the question in a second location makes sense :wink:

Anyway I linked this ticket from the answer that future readers will find both.
