### ISSUE TITLE
No NodeHandle::getParam() overload for float?

### ISSUE THREAD

**Issue by theidealist** [ros/roscpp_core#35]
I'm not sure if this is the correct project, but it seems like the correctly named one and I could not find which repo actually has node_handle.h.

In my version of ros (indigo), NodeHandle does not have a ::getParam() overload for float, the rationale for which is not clear.  This seems like a bug/oversight.

Thank you!

**Comment by dirk-thomas** [comment]
Can you please open a ticket in the following repository which contains the NodeHandle class: https://github.com/ros/ros_comm and then close this one.

**Update:** never mind, I will answer below - no need to move the ticket and then close it there.

**Comment by dirk-thomas** [comment]
The parameter server only stores double values - never float values. Therefore the `NodeHandle` API only exposes `getParam()` with `double` and leaves the conversion (with potential precision loss) to the user.

The choice for not storing floats natively on the parameter server is related to cross language support: http://answers.ros.org/question/10938/why-cant-you-use-floats-for-accessing-parameters-in-roscpp/

Based on that I don't think the function is missing is not an oversight but intended.

**Comment by theidealist** [comment]
Thanks @dirk-thomas, I'll move it there for confirmation you're right (sounds plausible anyway)
