### ISSUE TITLE
WallRate and Rate have different constructors

### ISSUE THREAD

**Issue by NikolasE** [ros/roscpp_core#38]
Even though WallRate and Rate have the same function and should have the same interface, their constructors work differently:

```
Rate::Rate(const Duration& d)
  : start_(Time::now())
  , expected_cycle_time_(d.sec, d.nsec)
  , actual_cycle_time_(0.0)
{ }

WallRate::WallRate(const Duration& d)
: start_(WallTime::now())
, expected_cycle_time_(1.0 / d.toSec())
, actual_cycle_time_(0.0)
{}
```

So if you exchange both classes, you have a different cycle time which is really suprising. The wiki also says that they should have the same interface:

http://wiki.ros.org/roscpp/Overview/Time

**Comment by dirk-thomas** [comment]
It looks like the `Rate` constructor was fixed in #26 but the `WallRate` constructor was not. I made a PR for this: #40.
