### ISSUE TITLE
Unused parameter warnings prevent clean builds.

### ISSUE THREAD

**Issue by aleeper** [ros/roscpp_core#41]
message_traits.h has several unused parameter violations, for example [here on line 171](https://github.com/ros/roscpp_core/blob/indigo-devel/roscpp_traits/include/ros/message_traits.h#L171).
All the offending lines are (171, 172, 190, 191, 210, 211).

For a project that wants to build with warnings-as-errors, this requires us to disable these warnings for any file that includes ROS messages, which is unfortunate.

I previously pushed to have the same issue fixed in dynamic reconfigure [here](https://github.com/ros/dynamic_reconfigure/issues/50). As you can see, the solution is just to comment out the parameter name when it's not used in a particular implementation.
e.g.

```
static std_msgs::Header* pointer(M& /*m*/) { return 0; }
```

**Comment by dirk-thomas** [comment]
Please consider to provide a PR for this.
