### ISSUE TITLE
Fix Serializer<bool> on ARM

### ISSUE THREAD

**Issue by tho-** [ros/roscpp_core#42]
Here is a patch fixing an issue with bool serialization on ARM.

[bool-serialization.diff.txt](https://github.com/ros/roscpp_core/files/115474/bool-serialization.diff.txt)

**Comment by dirk-thomas** [comment]
With a short test I was able to send messages containing boolean fields from ARM to non-ARM without any problem.

Please provide more information about:
- what exactly you tested
- what the expected and actual behavior was
- a [sscce](http://sscce.org) to reproduce the problem

Also instead of providing a diff file please consider creating a pull request.

**Comment by tho-** [comment]
I thought it was so simple that I didn't want to bother you with details. "sizeof(1)" obviously makes no sense here, it looks more like a typo than a bug. Anyway, here you go:

On x86_64:

```
cricket[~] > cat test-bool-serializer.cc
#include "ros/serialization.h"

int
main()
{
  uint8_t c[1];
  ros::serialization::Serializer<bool> s;
  ros::serialization::OStream o(c, sizeof(c));

  s.write(o, true);
  return 0;
}
cricket[~] > uname -m
x86_64
cricket[~] > source /opt/ros/indigo/setup.zsh
cricket[~] > g++ test-bool-serializer.cc -L/opt/ros/indigo/lib -lroscpp_serialization
cricket[~] > ./a.out
cricket[~] > echo $?
0
```

While on arm:

```
alexanor[~] > uname -m
armv7l
alexanor[~] > source /opt/ros/indigo/setup.zsh
alexanor[~] > g++ test-bool-serializer.cc -L/opt/ros/indigo/lib -lroscpp_serialization
alexanor[~] > ./a.out
terminate called after throwing an instance of 'ros::serialization::StreamOverrunException'
  what():  Buffer Overrun
zsh: abort (core dumped)  ./a.out
alexanor[~]!> echo $?
134
```

**Comment by tho-** [comment]
If you prefer, you can also pull the commit from there:
`git pull --rebase http://homepages.laas.fr/mallet/roscpp_core.git indigo-devel`

**Comment by dirk-thomas** [comment]
Thank you for providing the example snippet. The problem doesn't happen when using message serialization and therefore I could reproduce this without. Only in the above example which uses a custom buffer (which doesn't have more bytes to accommodate the extra three bytes) I was able to reproduce the problem and also confirm that the patch you recommended addresses the problem.
