### ISSUE TITLE
int8 values are printed as unsigned values

### ISSUE THREAD

**Issue by meyerj** [ros/roscpp_core#6]
Negative int8_t values are printed as very large integers near 2^32 as they are casted to a uint32_t in the specialization of the ros::message_operations::Printer<int8_t> class. I assume this is copy&paste bug from the uint8_t case and

```
s << (uint32_t)value << "\n";
```

in line 56 of message_operations.h should be replaced by

```
s << (int32_t)value << "\n";
```

or even better by a static_cast.

**Comment by wjwwood** [comment]
Function in question: https://github.com/ros/roscpp_core/blob/master/roscpp_traits/include/ros/message_operations.h#L54

**Comment by wjwwood** [comment]
See: #7
