### ISSUE TITLE
Assignment in `operator==`

### ISSUE THREAD

**Issue by zivsha** [ros/roscpp_core#65]
`message_event.h`  contains the following equals operator:

https://github.com/ros/roscpp_core/blob/3b362ac2369158faaaec9a5734bdd08cf341a2d9/roscpp_traits/include/ros/message_event.h#L201-L205

Which assigns the `rhs.message_` to the `message_` member, instead of comparing them.

**Comment by dirk-thomas** [comment]
Thank you for reporting this. Please see #66 which should fix the problem.
