### ISSUE TITLE
the destructor of DurationBase is not virtual

### ISSUE THREAD

**Issue by csukuangfj** [ros/roscpp_core#86]
See the code

https://github.com/ros/roscpp_core/blob/d2bb8cbcfd4944e48d16cdb20edfab5d225db265/rostime/include/ros/duration.h#L79

https://github.com/ros/roscpp_core/blob/d2bb8cbcfd4944e48d16cdb20edfab5d225db265/rostime/include/ros/duration.h#L108

**Comment by dirk-thomas** [comment]
The proposal has changed to remove the destructor in #104.
